os: osx
osx_image: xcode8.3
cache:
  directories:
  - node_modules
  - "$HOME/.cache"
install:
- nvm install 7
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- yarn
script:
- yarn run build
branches:
  only:
  - master
