branches:
  only:
    - master

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"
  kraken_version: "3.6.1"
  local_app_data: '%LOCALAPPDATA%'
  matrix:
    - kraken_platform: win64
      PLATFORM: x64
    - kraken_platform: win32
      PLATFORM: x86

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

# Install scripts. (runs after repo cloning)
install:
  - ps: Start-FileDownload https://release.gitkraken.com/$env:kraken_platform/GitKrakenSetup.exe
  - GitKrakenSetup.exe /verysilent /nolaunch
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

build_script:
  - ps: copy $env:local_app_data\gitkraken\app-$env:kraken_version\resources\app.asar app.asar.original
  - ps: Copy-Item -Path $env:local_app_data\gitkraken\app-$env:kraken_version\resources\app.asar.unpacked\ -Destination app.asar.original.unpacked -Recurse
  - npm run extract
  - npm run localize:win:jp
  - npm run pack
  - ps: .\createPatch.ps1 $env:kraken_version $env:kraken_platform

test: off

artifacts:
  - path: 'patches\*.patch'
    name: patch